name: Check Setup Status

on:
  workflow_dispatch:
  schedule:
    # Проверяем каждый день в 12:00 UTC
    - cron: '0 12 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Secrets Setup
        # Note: Context access warnings are expected when secrets are not yet configured
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "🔍 Проверка настройки GitHub Secrets для развертывания..."
          echo ""
          
          SETUP_COMPLETE=true
          
          # Проверяем HOST
          if [ -n "$HOST" ]; then
            echo "✅ HOST: настроен"
          else
            echo "❌ HOST: НЕ настроен"
            SETUP_COMPLETE=false
          fi
          
          # Проверяем USERNAME
          if [ -n "$USERNAME" ]; then
            echo "✅ USERNAME: настроен"
          else
            echo "❌ USERNAME: НЕ настроен"
            SETUP_COMPLETE=false
          fi
          
          # Проверяем PRIVATE_KEY
          if [ -n "$PRIVATE_KEY" ]; then
            echo "✅ PRIVATE_KEY: настроен"
          else
            echo "❌ PRIVATE_KEY: НЕ настроен"
            SETUP_COMPLETE=false
          fi
          
          # Проверяем PORT (опционально)
          if [ -n "$PORT" ]; then
            echo "✅ PORT: настроен ($PORT)"
          else
            echo "ℹ️ PORT: не настроен (будет использован порт 22)"
          fi
          
          echo ""
          
          if [ "$SETUP_COMPLETE" = true ]; then
            echo "🎉 Все секреты настроены! Развертывание готово к работе."
            echo ""
            echo "📝 Следующие шаги:"
            echo "1. Включите автоматическое развертывание в main.yml"
            echo "2. Протестируйте подключение с помощью 'Test SSH Connection'"
            echo "3. Запустите развертывание"
          else
            echo "⚠️ Настройка не завершена!"
            echo ""
            echo "📋 Что нужно сделать:"
            echo "1. Перейдите: https://github.com/${{ github.repository }}/settings/secrets/actions"
            echo "2. Добавьте недостающие секреты"
            echo "3. Следуйте инструкциям в SETUP_SECRETS_STEP_BY_STEP.md"
            echo ""
            echo "❌ Развертывание не будет работать до настройки всех секретов"
          fi
          
          echo ""
          echo "📚 Полезные ссылки:"
          echo "- Настройка секретов: https://github.com/${{ github.repository }}/settings/secrets/actions"
          echo "- Пошаговая инструкция: SETUP_SECRETS_STEP_BY_STEP.md"
          echo "- Подробное руководство: GITHUB_SECRETS_SETUP.md"

      - name: Repository Info
        run: |
          echo ""
          echo "📊 Информация о репозитории:"
          echo "- Репозиторий: ${{ github.repository }}"
          echo "- Ветка: ${{ github.ref_name }}"
          echo "- Коммит: ${{ github.sha }}"
          echo "- Актор: ${{ github.actor }}"
          echo "- Время: $(date)"
