name: Debug Secrets Configuration

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets availability
        # Note: Context access warnings are expected when secrets are not yet configured
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "🔍 Checking GitHub Secrets configuration..."
          echo ""
          
          # Проверяем наличие секретов (без вывода значений)
          if [ -n "$HOST" ]; then
            echo "✅ HOST secret is configured"
          else
            echo "❌ HOST secret is NOT configured"
          fi
          
          if [ -n "$USERNAME" ]; then
            echo "✅ USERNAME secret is configured"
          else
            echo "❌ USERNAME secret is NOT configured"
          fi
          
          if [ -n "$PRIVATE_KEY" ]; then
            echo "✅ PRIVATE_KEY secret is configured"
          else
            echo "❌ PRIVATE_KEY secret is NOT configured"
          fi
          
          if [ -n "$PORT" ]; then
            echo "✅ PORT secret is configured (value: $PORT)"
          else
            echo "ℹ️ PORT secret is not configured (will use default: 22)"
          fi
          
          echo ""
          echo "📋 Required secrets for deployment:"
          echo "   1. HOST - Your server IP address or domain"
          echo "   2. USERNAME - SSH username for server access"
          echo "   3. PRIVATE_KEY - SSH private key content"
          echo "   4. PORT - SSH port (optional, defaults to 22)"
          echo ""
          echo "🔧 To configure secrets:"
          echo "   1. Go to repository Settings"
          echo "   2. Navigate to Secrets and variables → Actions"
          echo "   3. Click 'New repository secret'"
          echo "   4. Add each required secret"
          echo ""
          echo "📖 For detailed instructions, see GITHUB_SECRETS_SETUP.md"

      - name: Test environment variables
        run: |
          echo "🧪 Testing environment variables..."
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
