name: Deploy Frontend

on:
  # Временно отключено до настройки GitHub Secrets
  # push:
  #   branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          echo "🔍 Validating GitHub Secrets..."
          MISSING_SECRETS=""
          
          if [ -z "${{ secrets.HOST }}" ]; then
            echo "❌ HOST secret is missing"
            MISSING_SECRETS="$MISSING_SECRETS HOST"
          else
            echo "✅ HOST secret is configured"
          fi
          
          if [ -z "${{ secrets.USERNAME }}" ]; then
            echo "❌ USERNAME secret is missing"
            MISSING_SECRETS="$MISSING_SECRETS USERNAME"
          else
            echo "✅ USERNAME secret is configured"
          fi
          
          if [ -z "${{ secrets.PRIVATE_KEY }}" ]; then
            echo "❌ PRIVATE_KEY secret is missing"
            MISSING_SECRETS="$MISSING_SECRETS PRIVATE_KEY"
          else
            echo "✅ PRIVATE_KEY secret is configured"
          fi
          
          if [ -n "$MISSING_SECRETS" ]; then
            echo ""
            echo "💡 Missing secrets:$MISSING_SECRETS"
            echo ""
            echo "🔧 To fix this:"
            echo "1. Go to https://github.com/${{ github.repository }}/settings/secrets/actions"
            echo "2. Click 'New repository secret'"
            echo "3. Add the missing secrets with proper values"
            echo ""
            echo "📖 See GITHUB_SECRETS_SETUP.md for detailed instructions"
            exit 1
          fi
          
          echo "✅ All required secrets are configured"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT || '22' }}
          script_stop: true
          script: |
            set -e
            cd /var/www/frontend_axenta

            echo "🔧 Starting deployment process..."
            echo "📍 Current directory: $(pwd)"
            echo "📍 Current branch: $(git branch --show-current)"
            echo "📍 Current commit: $(git rev-parse --short HEAD)"

            # Настраиваем Git для избежания проблем с divergent branches
            echo "⚙️ Configuring Git..."
            git config pull.rebase false
            git config --global --add safe.directory $(pwd)

            # Загружаем все изменения
            echo "📥 Fetching changes..."
            git fetch --all --prune

            # Проверяем, есть ли расходящиеся ветки
            LOCAL=$(git rev-parse HEAD)
            REMOTE=$(git rev-parse origin/main)

            if [ "$LOCAL" != "$REMOTE" ]; then
              echo "⚠️ Local and remote branches are different"
              echo "Local:  $LOCAL"
              echo "Remote: $REMOTE"
              echo "🔄 Performing hard reset to origin/main..."
              git reset --hard origin/main
              echo "✅ Repository updated to latest version"
            else
              echo "✅ Repository is already up to date"
              git pull origin main || git reset --hard origin/main
            fi

            # Показываем текущее состояние
            echo "📍 Updated to commit: $(git rev-parse --short HEAD)"
            echo "📍 Commit message: $(git log -1 --pretty=%B)"

            # Устанавливаем зависимости
            echo "📦 Installing dependencies..."
            /usr/bin/npm install

            # Собираем проект
            echo "🏗️ Building project..."
            /usr/bin/npm run build

            # Перезагружаем nginx
            echo "🔄 Reloading nginx..."
            sudo systemctl reload nginx

            echo "🎉 Deployment completed successfully!"
