name: Deploy (git pull over SSH)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare ~/.ssh
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" -T 5 "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: SSH and git pull
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
script: |
  set -e
  # Настройка Git для CI/CD
  git config --global user.email "ci@axenta.com"
  git config --global user.name "CI/CD Bot"
  
  cd "${{ secrets.REPO_PATH }}"
  git fetch --all --prune
  git pull origin "${{ secrets.BRANCH || 'main' }}"
  /usr/bin/npm install
  /usr/bin/npm run build
  sudo systemctl reload nginx
