name: Deploy Frontend

on:
  # Временно отключено до настройки GitHub Secrets
  # push:
  #   branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check deployment configuration
        id: check-deploy
        run: |
          echo "🔍 Checking deployment configuration..."
          
          if [ -z "${{ secrets.HOST }}" ] || [ -z "${{ secrets.USERNAME }}" ] || [ -z "${{ secrets.PRIVATE_KEY }}" ]; then
            echo ""
            echo "⚠️  Deployment secrets are not configured. Skipping deployment."
            echo ""
            echo "🎉 Code changes have been successfully pushed to GitHub!"
            echo ""
            echo "📋 To enable automatic deployment, configure these GitHub Secrets:"
            echo "   • HOST - Your server IP address or domain"
            echo "   • USERNAME - SSH username for server access"
            echo "   • PRIVATE_KEY - SSH private key content"
            echo "   • PORT - SSH port (optional, defaults to 22)"
            echo ""
            echo "🔧 How to configure secrets:"
            echo "   1. Go to https://github.com/${{ github.repository }}/settings/secrets/actions"
            echo "   2. Click 'New repository secret'"
            echo "   3. Add each required secret with proper values"
            echo ""
            echo "📖 For detailed instructions, see GITHUB_SECRETS_SETUP.md"
            echo ""
            echo "🚀 Once configured, the next push will automatically deploy to your server."
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          else
            echo "✅ All deployment secrets are configured"
            echo "🚀 Proceeding with deployment..."
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          fi

      - name: Deploy via SSH
        if: steps.check-deploy.outputs.should_deploy == 'true' && secrets.HOST != '' && secrets.USERNAME != '' && secrets.PRIVATE_KEY != ''
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT || '22' }}
          script_stop: true
          script: |
            set -e
            cd /var/www/frontend_axenta

            echo "🔧 Starting deployment process..."
            echo "📍 Current directory: $(pwd)"
            echo "📍 Current branch: $(git branch --show-current)"
            echo "📍 Current commit: $(git rev-parse --short HEAD)"

            # Настраиваем Git для избежания проблем с divergent branches
            echo "⚙️ Configuring Git..."
            git config pull.rebase false
            git config --global --add safe.directory $(pwd)

            # Загружаем все изменения
            echo "📥 Fetching changes..."
            git fetch --all --prune

            # Проверяем, есть ли расходящиеся ветки
            LOCAL=$(git rev-parse HEAD)
            REMOTE=$(git rev-parse origin/main)

            if [ "$LOCAL" != "$REMOTE" ]; then
              echo "⚠️ Local and remote branches are different"
              echo "Local:  $LOCAL"
              echo "Remote: $REMOTE"
              echo "🔄 Performing hard reset to origin/main..."
              git reset --hard origin/main
              echo "✅ Repository updated to latest version"
            else
              echo "✅ Repository is already up to date"
              git pull origin main || git reset --hard origin/main
            fi

            # Показываем текущее состояние
            echo "📍 Updated to commit: $(git rev-parse --short HEAD)"
            echo "📍 Commit message: $(git log -1 --pretty=%B)"

            # Устанавливаем зависимости
            echo "📦 Installing dependencies..."
            /usr/bin/npm install

            # Собираем проект
            echo "🏗️ Building project..."
            /usr/bin/npm run build

            # Перезагружаем nginx
            echo "🔄 Reloading nginx..."
            sudo systemctl reload nginx

            echo "🎉 Deployment completed successfully!"
