name: Protect Workflows Directory

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:
  check-workflow-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            .github/workflows/**
      
      - name: Check if workflows were modified
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "❌ ВНИМАНИЕ: Обнаружены изменения в .github/workflows/"
          echo ""
          echo "🚫 Изменения в папке .github/workflows запрещены по соображениям безопасности!"
          echo ""
          echo "📝 Измененные файлы:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "  - $file"
          done
          echo ""
          echo "🔧 Если изменения необходимы:"
          echo "  1. Обратитесь к администратору проекта"
          echo "  2. Создайте отдельный issue с обоснованием изменений"
          echo "  3. Получите одобрение от владельца репозитория"
          echo ""
          echo "⚠️  Данный pull request будет заблокирован до получения одобрения."
          exit 1
      
      - name: Success message
        if: steps.changed-files.outputs.any_changed == 'false'
        run: |
          echo "✅ Изменения в .github/workflows не обнаружены. Все в порядке!"

  require-admin-approval:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, '.github/workflows')
    steps:
      - name: Check if user is admin
        uses: actions/github-script@v7
        with:
          script: |
            const { data: user } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.actor
            });
            
            if (user.permission !== 'admin' && user.permission !== 'write') {
              core.setFailed('❌ Только администраторы могут изменять .github/workflows');
            } else {
              console.log('✅ Пользователь имеет права администратора');
            }
      
      - name: Add protection comment
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🚫 Изменения в .github/workflows заблокированы

### ⚠️ Причина блокировки:
Изменения в папке \`.github/workflows/\` запрещены по соображениям безопасности.

### 🔧 Что делать:
1. **Обратитесь к администратору** проекта для получения одобрения
2. **Опишите причину** необходимых изменений
3. **Дождитесь одобрения** от владельца репозитория

### 📋 Измененные файлы:
$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | sed 's/^/- /')

### 🛡️ Безопасность:
Workflow файлы могут выполнять произвольный код и имеют доступ к секретам репозитория. Поэтому их изменение требует особого контроля.

---
*Этот комментарий создан автоматически системой защиты workflows.*`
            })
